extraction:
  cpp:
    after_prepare: 
      - python report.py 60
  cobol:
    after_prepare: 
      - python report.py 60
  csharp:
    after_prepare: 
      - python report.py 60
  java:
    after_prepare: 
      - python report.py 60
  javascript:
    after_prepare: 
      - python report.py 60
  python:
    after_prepare: 
      - python report.py 60
